% Main script to create conditional statistics computation scripts for multiple fields
% This script calls write_cCond_mat_script for each specified field
clear all;
clc;

% Add functions directory to path
addpath('functions');

% Define all fields to process
field_list = {
    'Heatrelease';           % Heat Release Rate
    'density';          % Density  
    'temperature';            % Temperature
    'SYm_CH4';      % Methane Mass Fraction (Symmetry)
    'SYm_O2';       % Oxygen Mass Fraction (Symmetry) 
    'SYm_CO2';      % Carbon Dioxide Mass Fraction (Symmetry)
    'SYm_H2O';      % Water Mass Fraction (Symmetry)
    'CH4';          % Methane Mass Fraction
    'O2';           % Oxygen Mass Fraction
    'CO2';          % Carbon Dioxide Mass Fraction
    'H2O';          % Water Mass Fraction
};

% Common parameters for all fields
common_params = struct(...
    'LESStart', 201, ...
    'LESEnd', 1001, ...
    'Yu', 0.222606, ...
    'Yb', 0.0423208, ...
    'delC', 0.015, ...
    'D', 2e-3, ...
    'xlim_factor', 5, ...
    'zlim_factor', 10, ...
    'OutputDir', 'C_cond_fields_800_10D', ...
    'WorkDir', '/work/home/anindya/Anindya_Cases/CH4_jet_PF/2025_Runs/LES_base_case_v6/Chem_src_term_computation', ...
    'NumWorkers', 24);

fprintf('Creating conditional statistics computation scripts...\n');
fprintf('Total fields to process: %d\n\n', length(field_list));

% Loop through each field and create the script
for i = 1:length(field_list)
    field_name = field_list{i};
    
    fprintf('Processing field %d/%d: %s\n', i, length(field_list), field_name);
    
    try
        % Call write_cCond_mat_script with field-specific parameters
        write_cCond_mat_script(...
            'FieldName', field_name, ...
            'LESStart', common_params.LESStart, ...
            'LESEnd', common_params.LESEnd, ...
            'Yu', common_params.Yu, ...
            'Yb', common_params.Yb, ...
            'delC', common_params.delC, ...
            'D', common_params.D, ...
            'xlim_factor', common_params.xlim_factor, ...
            'zlim_factor', common_params.zlim_factor, ...
            'OutputDir', common_params.OutputDir, ...
            'WorkDir', common_params.WorkDir, ...
            'NumWorkers', common_params.NumWorkers);
        
        fprintf('  ✓ Created script: Ccond_stats_computation_%s.m\n', field_name);
        
    catch ME
        fprintf('  ✗ Error creating script for %s: %s\n', field_name, ME.message);
    end
end

fprintf('\nScript generation completed!\n');
fprintf('Generated scripts can be found in the current directory.\n');
